name: deploy to github pages 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: build 
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          wasm-pack build --target web --out-dir build/pkg

      - name: deploy
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout gh-pages
          git rebase main
          git add -f build/
          git commit -m "deploy" || echo "no changes to commit"
          git push -f origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}