name: deploy to github pages 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: test-deploy 
          fetch-depth: 0

      - name: build 
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          wasm-pack build --target web --out-dir build/pkg

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "18.16.1"
      
      - name: build react app
        run: |
          cd ui
          npm install
          npm install ../build/pkg
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ui/build 
